### ISSUE TITLE
Feature Request: Update available hook

### ISSUE THREAD

**Issue by NullVoxPopuli** [DockYard/ember-service-worker-asset-cache#36]
I think it'd be cool to have a built-in way to have a "There is an update available" hook somewhere in an app using ember-service-workers. 
mayyybe it could be a service? so that way devs could use their own toasting / notification libraries that are already being used in the rest of the app?

**Comment by eshtadc** [comment]
I know this issue is super-old... going through and doing some maintenance to these repos. I believe you have already found https://github.com/topaxi/ember-service-worker-update-notify based on some of our interactions in `ember-service-worker`. Does that address the request or should we be brainstorming something additional?

**Comment by NullVoxPopuli** [comment]
it does! 
and I even submitted a PR (that got merged) to that repo to make the update check be a polling-type-dealio.

thanks!
